### PR TITLE
Fixed the state refresh issue in the controller

### PR DESCRIPTION
**Pull request by ruwiss**
Performed a replace operation due to incorrect state naming.
Removed the `stateName` parameter from the Stateful Widget due to issues with custom state names.
Added the `notifyListeners` method to align with the conventional state update approach.

### CODE REVIEW

**Comment by agordn52** [comment]
Hi @ruwiss,

Thanks for the PR, I'll review this tomorrow.

**Comment by ruwiss** [comment]
Note: We don't have to give a function in setState(() {}). If we put a function in it, it should have small operations. Otherwise the state will not be updated. For this reason usually,
```dart
function();
```
then
```dart
setState(() {});
```
is used as

**Comment by agordn52** [comment]
> Note: We don't have to give a function in setState(() {}). If we put a function in it, it should have small operations. Otherwise the state will not be updated. For this reason usually,
> 
> ```dart
> 
> function();
> 
> ```
> 
> then
> 
> ```dart
> 
> setState(() {});
> 
> ```
> 
> is used as

Thanks for the information, I'm looking into this now

**Comment by agordn52** [comment]
Resolved in `nylo_support: 6.12.2`

**Pull request closed without merging**
