### PR TITLE
fix router navigate function

### PR DESCRIPTION
**Pull request by lpdevit**
transitionDuration was not implemented

### CODE REVIEW

**Comment by agordn52** [comment]
Appreciate the PR. 

This fixes the `TransitionDuration` argument for the router, I'll get this merged in 🚀

**Comment by lpdevit** [comment]
Thank you Anthony! I don't know what's your usual workflow: are you going to do a release with this fix so that we can use it in our projects?

**Comment by agordn52** [comment]
Hi @lpdevit,

I'll create a new release for later today (**v3.2.0**).

When it's live on https://pub.dev I'll ping a notification here 🚨

**Comment by lpdevit** [comment]
> Hi @lpdevit,
> 
> 
> 
> I'll create a new release for later today (**v3.2.0**).
> 
> 
> 
> When it's live on https://pub.dev I'll ping a notification here 🚨

Thank you and have a great day! 💪🏼💪🏼💪🏼

**Pull request merged**
